### ISSUE TITLE
Creative Assignment One ready for grading

### ISSUE THREAD

**Issue by whytnestevens** [VIS-2129-F2020/whytnestevens-vis#1]
Would also like to know how to stretch graph so labels aren't scrunched together

**Comment by bauranov** [comment]
Overall, nice work!

- You can avoid having the loading messages clutter your html file by starting a chunk with {r, message=FALSE}.
- I like theme_solarized(), easy on the eyes.
- You can use scale_x_discrete(guide = guide_axis(n.dodge=3)) to stagger labels to avoid overlap. I would also rename N/A variable to something shorter. That way you both extend the chart and shorten the label size. Finally, you can place the legend below the chart which will stretch it and leave more room for labels. You can place the legend below the chart with theme(legend.position="bottom").

Keep up the good work!
