### ISSUE TITLE
Creative Assignment 2 ready for grading

### ISSUE THREAD

**Issue by whytnestevens** [VIS-2129-F2020/whytnestevens-vis#2]
Thanks for the help Carole! Also would be interested in knowing how to get the Dorling Cartogram to work as I kept getting error messages

**Comment by bauranov** [comment]
Great work! Here are some comments:
- Please add a link to your HTML file with https://vis-2129-f2020.github.io/whytnestevens-vis/filename, where *filename* is the name of your HTML file. 
- You can remove warnings from the HTML by adding {r,warning=FALSE} at the beginning of the code chunk.
- Proportional Symbol Map: it looks like the legend is too big, you can either use theme(legend.key.size=unit()), or reduce the number of labels.
- Consider adding names of the countries to the map.
- If you'd like, you can set office hours with one of us to work on Dorling Cartogram.

Keep up the good work!
