### ISSUE TITLE
Assignment 4 ready for grading

### ISSUE THREAD

**Issue by whytnestevens** [VIS-2129-F2020/whytnestevens-vis#4]
link: https://vis-2129-f2020.github.io/whytnestevens-vis/CreativeAssignmentFour.html

**Comment by bauranov** [comment]
Great work, you did a lot here. I wonder if any ideas come to mind on how to increase the accessibility of Metro stops outside of the city center? Before you submit the html, make sure there aren't any unwanted messages and warnings.
